# This is a basic workflow to help you get started with Actions

name: GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cd dir
        run: |
          cd __test__

      - name: Install Dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm build
